version: '3'

networks:
  networks_bank:
    driver: bridge

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - networks_bank
